namenode:
    image: hadoop
    ports: 
        - "50070:50070"
    command: hdfs namenode
    hostname: hdfs-namenode

datanode:
    image: hadoop
    command: hdfs datanode
    ports:
        - "50075"
    links:
        - namenode:hdfs-namenode

secondarynamenode:
    image: hadoop
    command: hdfs secondarynamenode
    ports:
        - "50090:50090"
    links:
        - namenode:hdfs-namenode
